// autogenerated by Processing revision 1292 on 2023-03-11

import processing.core.PApplet;
import processing.core.PImage;

import java.io.*;

/**
 * @author Langdon S.
 */


@SuppressWarnings("StatementWithEmptyBody")
public class pac_man extends PApplet {
    // By Langdon S.
    //current version:
    final static String TITLE = "Pac-Man 10.5";
    //
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|
//            G A M E  S E T T I N G S            |
    final static boolean startsWMouth = false; //        |
    final static boolean eyesMove = true; //             |
    final static boolean showGhostWhenStopped = true;//  |
    //final static boolean useOpenGL = true;//           |
    // final static boolean other = false; //               |
    final static float ghostSpeed = 2; //                |
    final static float pacmanSpeed = 3; //               |
    //final static boolean turnAround = true; //         |
    final static float cellWidth = 32;
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|
    final static int pelletWorth = 10, canvasWidth = (int) (cellWidth * 13), canvasHeight = (int) (cellWidth * 13f), gSize = 2;
    final static String[] fruitPoints = {"cherry", "strawberry", "orange", "orange", "apple", "apple", "melon", "melon", "galaxian", "galaxian", "bell", "bell", "key", "key"};
    final static byte[][] gDesign = {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0}, {0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, {0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, {0, 0, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0}, {0, 0, 1, 2, 3, 3, 2, 1, 1, 2, 3, 3, 2, 1, 0, 0}, {0, 1, 1, 2, 3, 3, 2, 1, 1, 2, 3, 3, 2, 1, 1, 0}, {0, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 0}, {0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, {0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, {0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, {0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, {0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0}, {0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}};
    final static int[][] altGhostBottom = {{0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0}, {0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0}};
    final static boolean[][] cellMap = {{false, true, false, true, true, true, true, true, true, true, true, true}, {false, true, true, true, false, false, false, false, false, false, false, true}, {false, true, false, true, true, true, true, true, true, true, false, true}, {false, true, false, true, false, false, false, false, false, true, false, true}, {false, true, true, true, true, true, true, true, true, true, true, true}, {false, true, false, true, false, true, false, false, true, false, true, true}, {false, true, false, true, false, true, false, true, true, false, true, true}, {false, true, false, true, true, true, true, false, true, false, false, true}, {false, true, false, false, false, true, false, false, true, false, true, true}, {false, true, true, true, true, true, true, false, true, false, true, true}, {false, true, true, false, false, false, true, true, true, false, true, true}};
    final Ghost ghost1 = new Ghost();
    final Ghost ghost2 = new Ghost();
    final Ghost ghost3 = new Ghost();
    final Pacman pacman = new Pacman();
    final Cell[][] cells = {new Cell[13], new Cell[13], new Cell[13], new Cell[13], new Cell[13], new Cell[13], new Cell[13], new Cell[13], new Cell[13], new Cell[13], new Cell[13], new Cell[13], new Cell[13]};
    final Pixel[][] ghostPx = {new Pixel[16], new Pixel[16], new Pixel[16], new Pixel[16], new Pixel[16], new Pixel[16], new Pixel[16], new Pixel[16], new Pixel[16], new Pixel[16], new Pixel[16], new Pixel[16], new Pixel[16], new Pixel[16], new Pixel[16], new Pixel[16]};
    final Pixel[][] ghostBottom2Px = {new Pixel[16], new Pixel[16]};
    //final boolean updating = false;
    //Strings
    String path;
    //String OS = "unknown";
    //float updateVersion = version;
    int lives = 3; //                             |
    int chompSpeed = 8; //                        |
    boolean playStartSound = true; //             |
    boolean playPauseBeat = true; //              |
    //booleans
    boolean /*askToUpdate, */error, finishedDelay, first, first1 = true, lostLife, paused, pelletFirst, runSetup = true, start;
    //ints
    int startMillis, chomp = 30, cellCount, duration, durationStart, fruitWorth, highScore, level, livesClaimed, pelletErrors, pelletsEaten, score, startFrames;
    int coordsX, coordsY, coords3X, coords3Y, coords4X, coords4Y, coords5X, coords5Y;
    int prevHighScore;
    String[] messages = {};
    String errorInfo;
    float tempFPSVal;//, newVersion, updateVersion;
    PImage cherry, strawberry, apple, orange, melon, galaxian, bell, keyI, restartB, noPauseBeatB;
    Sound dieS, startSound, dotSound1, dotSound2, fruit, extra_life, pause, pause_beat;
    Pellet[] pellet = {};
    Coordinate[] coords2 = {};


    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ A FEW RANDOM FUNCTIONS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~///

    static public void main(String[] passedArgs) {
        String[] appletArgs = new String[]{"pac_man"};
        if (passedArgs != null) {
            PApplet.main(concat(appletArgs, passedArgs));
        } else {
            PApplet.main(appletArgs);
        }
    }

    public void settings() {
        /*if (useOpenGL) {
            size(canvasWidth, canvasHeight);
            smooth(8);
        } else {*/
        size(canvasWidth, canvasHeight);
        //}
    }

    public void setup() {
        surface.setTitle("Loading...");
        System.out.println("Please wait...");
        background(0);
        noStroke();
        textSize(20);
        textAlign(CENTER);
        fill(255);
        text("Loading...\nBy Langdon Staab\n\nSound manager by Tyler Tomas", Math.round(width / 2f), Math.round(height / 2f));
        frameRate(120);
        //check setup2() for setup
    }

    public void setup2() {
        noStroke();
        surface.setResizable(true);
        imageMode(CENTER);
        changeAppIcon();
        //displayDensity(2);

        //System.out.println(": "+);
        //System.out.println("DisplayDensity: "+displayDensity());
        //System.out.println("pixelHeight: "+pixelHeight);
        path = System.getProperty("user.home");

        String temp = loadString(path + "/highscore.txt");
        if (temp.equals("error")) {
            try {
                PrintWriter file = new PrintWriter(path + "/highscore.txt");
                file.println(0);
                file.close();
                prevHighScore = 0;
            } catch (FileNotFoundException e) {
                messages = splice(messages, "An error occurred while creating high score file", 0);
                System.err.println("An error occurred while creating the high score file.");
                logError(e);
                prevHighScore = 0;
                StringWriter sw = new StringWriter();
                PrintWriter pw = new PrintWriter(sw);
                e.printStackTrace(pw);
                errorInfo += sw.toString();
            }
        } else {
            prevHighScore = java.lang.Integer.parseInt(temp);
        }

        startSound = new Sound("game_start.wav");
        dotSound1 = new Sound("dot_1.wav");
        dotSound2 = new Sound("dot_2.wav");
        pause = new Sound("pause.wav");
        pause_beat = new Sound("pause_beat.wav");
        dieS = new Sound("death.wav");
        fruit = new Sound("fruit.wav");
        extra_life = new Sound("extra_life.wav");
        System.out.println("Sound load success!");

        cherry = loadImage("cherry.png");
        noPauseBeatB = loadImage("pause_beat off.png");
        restartB = loadImage("restart.png");
        strawberry = loadImage("strawberry.png");
        orange = loadImage("orange.png");
        apple = loadImage("apple.png");
        melon = loadImage("melon.png");
        System.out.println("Image load success!");

        createMaze();
        initializeMaze();
        makePelletCoords();
        pxInit();
        startMillis = millis();
        pellet[5].isFruit = true;
        surface.setTitle(TITLE);

        System.out.println("Setup success!");
    }

    public void logError(Exception e) {
        try {
            FileWriter fstream = new FileWriter(path + "/Desktop/pacmanerror.txt", true);
            BufferedWriter out = new BufferedWriter(fstream);
            PrintWriter pWriter = new PrintWriter(out, true);
            e.printStackTrace(pWriter);
        } catch (Exception ie) {
            System.err.println("Could not append Exception to logfile");

            errorInfo += "\n\n\n";
            StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);
            ie.printStackTrace(pw);
            System.err.println(sw);
            errorInfo += sw.toString();
        }
    }

    public String loadString(String filename) {
        String[] ret;
        String data;
        try {
            ret = loadStrings(filename);
            data = ret[0];
            return data;
        } catch (Exception ignored) {
            return "error";
        }
    }

    public void lazyLoad() {
        messages = splice(messages, "Loading more fruit sprites...", 0);
        galaxian = loadImage("galaxian.png");
        bell = loadImage("bell.png");
        keyI = loadImage("key.png");
        messages = splice(messages, "All fruit sprites loaded successfully.", 0);
    }

    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ MAIN PROGRAM ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
    public void draw() {
        try {
            if (error) {
                background(0);
                textAlign(LEFT, CENTER);
                text(errorInfo, 4, height / 2f);
                //} else if (updating) {
                //askUpdate();\
            } else if (runSetup) {
                setup2();
                runSetup = false;
                startFrames = frameCount;
                durationStart = millis();
                duration = 4500 + millis();
                startMillis = millis();
                println(millis());
            } else if (millis() < 2000) {
                //display loading screen for a minimum of 2 seconds.
                //wait until 2 seconds have passed

            } else if (lives <= 0) {
                background(0);
                fill(255, 64, 64);
                textAlign(CENTER);
                text("GAME OVER", canvasWidth / 2f, canvasHeight / 2f);
                text("Click the screen to play again", canvasWidth / 2f, canvasHeight / 2f + 40);
                if (mousePressed) {
                    restart();
                }
            } else {
                if (frameCount % 2 == 0 && !paused) {
                    if (millis() < duration) {
                        pacman.stop();
                        pacman.stopped = true;
                        finishedDelay = false;
                        ghost1.halt();
                        ghost2.halt();
                        ghost3.halt();
                        start = true;
                    } else if (!finishedDelay) {
                        start = true;
                        ghost1.up();
                        ghost2.up();
                        ghost3.up();
                        finishedDelay = true;
                    }

                    destroyUselessMessages();

                    ghostPx[1][1].colourInit();
                    coords3X = getGhostCoords(ghost1).x;
                    coords3Y = getGhostCoords(ghost1).y;
                    coords4X = getGhostCoords(ghost2).x;
                    coords4Y = getGhostCoords(ghost2).y;
                    coords5X = getGhostCoords(ghost3).x;
                    coords5Y = getGhostCoords(ghost3).y;
                    if (lostLife) {
                        if (chomp < 60) {
                            chomp++;
                        }
                        if (first1) {
                            first1 = false;
                            delay(100);
                            if (chomp < 60) {
                                chomp = 60;
                            }
                            dieS.play();
                        }
                        pacman.stop();
                        ghost1.halt();
                        ghost2.halt();
                        ghost3.halt();
                        if (dieS.isPlaying()) {
                            chomp += 3;
                        } else {
                            ghost1.newGame();
                            ghost2.newGame();
                            ghost3.newGame();
                            pacman.x = cellWidth * 1.5f;
                            pacman.y = cellWidth * 1.5f;
                            first1 = true;
                            lostLife = false;
                            chomp = 16;
                            duration = 2000 + millis();
                            ghost1.up();
                            ghost2.up();
                            ghost3.up();
                            pacman.stop();
                            pacman.stopped = true;
                            lives--;
                        }
                    }
                    if (!pacman.dir.equals("stopped")) {
                        if (chomp > 64) {
                            chompSpeed = -chompSpeed;
                        }
                        if (chomp < 4) {
                            chompSpeed = -chompSpeed;
                        }
                        chomp += chompSpeed;
                    }
                    if (pelletsEaten < pellet.length - 1 && !lostLife) {
                        pacman.update();
                    }
                    ghost1.update(coords3X, coords3Y);
                    ghost2.update(coords4X, coords4Y);
                    ghost3.update(coords5X, coords5Y);
                    ghost1.goodPosition(coords3X, coords3Y);
                    ghost2.goodPosition(coords4X, coords4Y);
                    ghost3.goodPosition(coords5X, coords5Y);
                    controlGhostMovement(coords3X, coords3Y, coords4X, coords4Y, coords5X, coords5Y);
                    for (int b = 0; b < coords2.length; b++) {
                        pellet[b].goodPosition(coords2[b].x, coords2[b].y);
                        pellet[b].isBEaten();
                    }

                    background(0);
                    showMaze(color(33, 33, 255), true);

                    if (pelletsEaten >= pellet.length - 1 && !lostLife) {
                        if (!first) {
                            first = true;
                            level++;
                            determineFruitType();
                            durationStart = millis();
                            duration = 2000 + millis();
                        }
                        ghost1.halt();
                        ghost2.halt();
                        ghost3.halt();
                        pacman.stop();
                        if ((millis() - durationStart < 250) || (millis() - durationStart < 750 && millis() - durationStart > 500) || (millis() - durationStart < 1250 && millis() - durationStart > 1000) || (millis() - durationStart < 1750 && millis() - durationStart > 1500)) {
                            showMaze(color(222, 222, 255), true);
                        }
                        if (millis() - durationStart >= 2000) {
                            //determineFruitType();
                            pacman.update();
                            ghost1.up();
                            ghost2.up();
                            ghost3.up();
                            pacman.stopped = true;
                            pacman.stop();
                            makePelletCoords();
                            pelletErrors = 0;
                            playStartSound = false;
                        }
                    }
                    display();
                    //pacman.update();
                    if (start) {
                        start = false;
                    }
                    //int useless = 5/0;
                }
                if (keyPressed) {
                    switch (keyCode) {
                        case UP, 87 -> pacman.up();
                        case DOWN, 83 -> pacman.down();
                        case RIGHT, 68 -> pacman.right();
                        case LEFT, 65 -> pacman.left();
                    }

                }
            }
        } catch (Exception e) {
            paused = true;
            StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);
            e.printStackTrace(pw);
            errorInfo += sw.toString();
            System.err.println(errorInfo);
            error = true;
            textSize(12);
            fill(255);
            windowResize(1000, canvasHeight);
            frameRate(30);
            logError(e);

        }
    }

    public void display() {
        /*if(frameCount%100 == 0){
        //System.out.println("Ghost1: "+ghost1.dir+"Ghost2: "+ghost2.dir+"Ghost3: "+ghost3.dir);
        }*/
        drawButtons();
        fill(255);
        textAlign(CENTER);
        textSize(12);
        text("HIGH SCORE\n" + highScore, width / 2f, 12);
        tempFPSVal = ((millis() - startMillis) / 1000f) > 0 ? ((millis() - startMillis) / 1000f) : 1;
        text(str(Math.round((frameCount - startFrames) / tempFPSVal)), 330, 10);
        showLives();
        noStroke();
        for (int b = 0; b < coords2.length; b++) {
            pellet[b].draw();
        }
        drawGhosts();
        textAlign(LEFT);
        displayMessages();
        pacman.show(chomp);
        if (lives <= 0) {
            background(0);
            fill(255, 0, 0);
            textAlign(CENTER);
            text("GAME OVER", canvasWidth / 2f, canvasHeight / 2f);
            text("Click the screen to play again", canvasWidth / 2f, canvasHeight / 2f + 40);
            if (mousePressed) {
                restart();
            }
        }
    }

    public void changeAppIcon() {
        getSurface().setIcon(loadImage("icon.png"));
    }

    public void displayMessages() {
        textSize(12);
        fill(0, 255, 50);
        for (int i = 0; i < messages.length; i++) {
            text(messages[i], 20, 20 + (i * 20));
        }
    }

    public void addLife() {
        lives++;
        livesClaimed++;
        extra_life.play();
        messages = splice(messages, "Claimed extra life!", 0);
    }

    public void giveLives() {
        if (score >= 1000 && livesClaimed < 1) {
            addLife();
        } else if (score >= 2000 && livesClaimed < 2) {
            addLife();
        } else if (score >= 5000 && livesClaimed < 3) {
            addLife();
        } else if (score >= 10000 && livesClaimed < 4) {
            addLife();
        } else if (score >= 20000 && livesClaimed < 5) {
            addLife();
        } else if (score >= 50000 && livesClaimed < 6) {
            addLife();
        } else if (score >= 100000 && livesClaimed < 7) {
            addLife();
        } else if (score >= 200000 && livesClaimed < 8) {
            addLife();
        } else if (score >= 500000 && livesClaimed < 9) {
            addLife();
        } else if (score >= 1000000 && livesClaimed < 10) {
            addLife();
        }
    }

    public int createPosition(boolean dirIsX) {
        int newPos = (int) (Math.round(random(cellWidth, canvasHeight - cellWidth * 2f) / cellWidth) * cellWidth + cellWidth / 2f);
        while (dirIsX && newPos <= cellWidth * 2.5f) {
            newPos = (int) (Math.round(random(cellWidth, canvasHeight - cellWidth * 2f) / cellWidth) * cellWidth + cellWidth / 2f);
        }
        return newPos;
    }

    public boolean hitBoxCollision(int cellX, int cellY, float objectX, float objectY) {
        return objectX > cellX && objectX < cellX + cellWidth && objectY > cellY && objectY < cellY + cellWidth;
    }

    public void makePelletCoords() {
        for (int i = 0; i < pellet.length; i++) {
            coords2[i].x = Math.round((pellet[i].x) / cellWidth + 0.5f) - 1;
            coords2[i].y = Math.round((pellet[i].y) / cellWidth + 0.5f) - 1;
        }
    }

    public void pxInit() {
        for (int i = 0; i < ghostPx.length; i++) {
            for (int j = 0; j < ghostPx.length; j++) {
                ghostPx[i][j] = new Pixel(gDesign[i][j], j * gSize, i * gSize);
            }
        }
        for (int i = 0; i < altGhostBottom.length; i++) {
            for (int j = 0; j < altGhostBottom[0].length; j++) {
                ghostBottom2Px[i][j] = new Pixel(altGhostBottom[i][j], j * gSize, (i + 13) * gSize);
            }
        }
    }


////// Calling Things //////

    public boolean checkGoodDir(String dir, int posX, int posY) {
        boolean goodDir = true;
        switch (dir) {
            case "up" -> {
                if (posY - 1 >= 0) {
                    goodDir = cells[posX][posY - 1].open;
                }
            }
            case "down" -> {
                if (posY + 1 <= height / cellWidth) {
                    goodDir = cells[posX][posY + 1].open;
                }
            }
            case "right" -> {
                if (posX + 1 <= width / cellWidth) {
                    goodDir = cells[posX + 1][posY].open;
                }
            }
            case "left" -> {
                if (posX - 1 >= 0) {
                    goodDir = cells[posX - 1][posY].open;
                }
            }
        }
        return !goodDir;
    }


//////// FUNCTIONS ////////

    public String makeDir(int Var) {
        return switch (Var) {
            case 0 -> "up";
            case 1 -> "down";
            case 2 -> "right";
            case 3 -> "left";
            default -> "stopped";
        };
    }

    public int makeDirNum() {
        float tempDirNum = random(-0.1f, 4);
        int dirNum = floor(tempDirNum);
        dirNum = constrain(dirNum, 0, 3);
        return dirNum;
    }

    public void createMaze() {
        for (int i = 0; i < cellMap[1].length + 1; i++) {
            for (int j = 0; j < cellMap[1].length + 1; j++) {
                cells[i][j] = new Cell(Math.round(i * cellWidth), Math.round(j * cellWidth));
            }
        }
    }

    public void initializeMaze() {
        for (Cell[] cell : cells) {
            cell[0].open = false;
            cell[cells.length - 1].open = false;
        }
        for (int i = 0; i < cells[0].length; i++) {
            cells[0][i].open = false;
            cells[cells.length - 1][i].open = false;
        }
        for (int row = 1; row < cellMap.length + 1; row++) {
            for (int col = 0; col < cellMap[row - 1].length; col++) {
                cells[col][row].open = cellMap[row - 1][col];
                if (cellMap[row - 1][col]) {
                    //noinspection StatementWithEmptyBody
                    if (col == 1 && row == 1) {
                    } else {
                        pellet = (Pellet[]) append(pellet, new Pellet(Math.round(col * cellWidth + cellWidth / 2), Math.round(row * cellWidth + cellWidth / 2)));
                        coords2 = (Coordinate[]) append(coords2, new Coordinate());
                        cellCount++;
                    }
                }
            }
        }
    }

    public void showMaze(int mazeColor, boolean all) {
        for (Cell[] cell : cells) {
            for (Cell value : cell) {
                value.show(mazeColor, all);
            }
        }
    }

    public void destroyUselessMessages() {
        while (messages.length > 6) {
            messages = shorten(messages);
        }
        if ((millis() - startMillis) % 25 == 0 && (millis() - startMillis) > 500 && messages.length > 0) {
            messages = shorten(messages);
        }
        if (messages.length > 4) {
            messages = shorten(messages);
        }
    }

    public void showLives() {
        float size = 20;
        float sizeT, sizeB;
        sizeT = map(size, 0, 60, 0, 0.52f);
        sizeB = map(size, 0, 60, TWO_PI, 5.76f);
        fill(255, 202, 0);
        for (int x = 1; x < lives; x++) {
            arc(25 * x, height - cellWidth / 2f, 20, 20, sizeT, sizeB);
        }
    }

    public void increaseHighScore() throws FileNotFoundException {
        if (prevHighScore > highScore) {
            highScore = prevHighScore;
        }
        if (score > highScore) {
            highScore = score;
        }
        if (highScore > prevHighScore) {
            //String[] newHighScore = {str(highScore)};
            //DataOutputStream dos = new DataOutputStream(new BufferedOutputStream(new FileOutputStream(path + "/settings.dat")));
            PrintWriter out = new PrintWriter(path + "/highscore.txt");
            //dos.writeInt(i);
            out.println(str(highScore));
            out.close();
            //saveStrings(path + "/highscore.txt", newHighScore);
        }
    }

    public void restart() {
        lives = 3;
        lostLife = false;
        level = 0;
        playStartSound = true;
        makePelletCoords();
        pacman.update();
        pacman.x = cellWidth * 1.5f;
        pacman.y = cellWidth * 1.5f;
        score = 0;
        determineFruitType();
        for (Pellet value : pellet) {
            value.update();
        }
        durationStart = millis();
        duration = 4500 + millis();
    }

    public void restartButton() {
        int x = Math.round(cellWidth * 4), y = Math.round(cellWidth * 12);
        if (hitBoxCollision(x, y, mouseX, mouseY)) {
            restart();
        }
    }

    public void pauseButton(boolean drawButton) {
        int x = Math.round(cellWidth * 5), y = Math.round(cellWidth * 12);
        if (drawButton) {
            rect(x, y, cellWidth, cellWidth);
        }
        if (hitBoxCollision(x, y, mouseX, mouseY)) {
            if (paused) {
                if (pause_beat.isPlaying()) {
                    pause_beat.stop();
                }
            } else {
                pause.play();
                if (playPauseBeat) {
                    pause_beat.loop();
                }
            }
            delay(10);
            paused = !paused;
        }
    }

    public void pauseBeatOffButton() {
        int x = Math.round(cellWidth * 3), y = Math.round(cellWidth * 12);
        if (hitBoxCollision(x, y, mouseX, mouseY)) {
            playPauseBeat = !playPauseBeat;
            messages = splice(messages, "You have turned pause_beat " + (playPauseBeat ? "on" : "off"), 0);
        }
    }

    public void drawButtons() {
        image(restartB, cellWidth * 4 + cellWidth / 2f, cellWidth * 12 + cellWidth / 2f, cellWidth, cellWidth);
        image(noPauseBeatB, cellWidth * 3 + cellWidth / 2f, cellWidth * 12 + cellWidth / 2f, cellWidth, cellWidth);
        fill(0);
        rect(cellWidth * 5.2f, cellWidth * 12.1f, cellWidth / 4f, cellWidth * 0.8f, 10);
        rect(cellWidth * 5.55f, cellWidth * 12.1f, cellWidth / 4f, cellWidth * 0.8f, 10);
    }

    public void determineFruitType() {
        if (level == 8) {
            println(fruitPoints[level]);
            lazyLoad();
        }
        if (level < fruitPoints.length) {
            pellet[5].fruitType = fruitPoints[level];
        } else {
            pellet[5].fruitType = fruitPoints[fruitPoints.length - 1];
        }
    }

    public void mouseClicked() {
        //if (!updating) {
        pauseBeatOffButton();
        restartButton();
        pauseButton(false);
        // }
    }

    public Coordinate getGhostCoords(Ghost curGhost) {
        float a = 3, b = 1;
        float offsetY = 0, offsetX = 0;
        Coordinate curGhostCoords = new Coordinate();
        switch (curGhost.dir) {
            case "up" -> offsetY += cellWidth / a + b;
            case "down" -> offsetY -= cellWidth / a + b;
            case "right" -> offsetX -= cellWidth / a + b;
            case "left" -> offsetX += cellWidth / a + b;
        }
        curGhostCoords.x = Math.round((curGhost.x + offsetX) / cellWidth + 0.5f) - 1;
        curGhostCoords.y = Math.round((curGhost.y + offsetY) / cellWidth + 0.5f) - 1;
        return curGhostCoords;
    }

    public void drawGhostEyes(Ghost cGhost) {
        int x = 7;
        int y = 11;
        rectMode(CORNER);
        rectMode(CORNER);
        fill(63, 0, 252);
        if (eyesMove) {
            switch (cGhost.dir) {
                case "up" -> y -= 2;
                case "down" -> y += 2;
                case "right" -> x += 2;
                case "left" -> x -= 2;
            }
        }
        rect(x, y, 4, 4);
        rect(x + 12, y, 4, 4);
    }

    public void drawGhosts() {
        if (!ghost1.dir.equals("stopped") || showGhostWhenStopped) {
            translate(ghost1.x - 15, ghost1.y - 15);
            for (int i = 0; i < ghostPx.length; i++) {
                for (int j = 0; j < ghostPx.length; j++) {
                    if ((i == 14 || i == 13) && (frameCount - startFrames) % 100 < 45) {
                        ghostBottom2Px[i - 13][j].colourInit();
                        ghostBottom2Px[i - 13][j].draw(color(208, 62, 25));
                    } else {
                        ghostPx[i][j].colourInit();
                        ghostPx[i][j].draw(color(208, 62, 25));
                    }
                }
            }
            drawGhostEyes(ghost1);
            resetMatrix();
        }
        if (!ghost2.dir.equals("stopped") || showGhostWhenStopped) {
            translate(ghost2.x - 15, ghost2.y - 15);
            for (int i = 0; i < ghostPx.length; i++) {
                for (int j = 0; j < ghostPx.length; j++) {
                    if ((i == 14 || i == 13) && (frameCount - startFrames) % 100 < 45) {
                        ghostBottom2Px[i - 13][j].colourInit();
                        ghostBottom2Px[i - 13][j].draw(color(234, 130, 229));
                    } else {
                        ghostPx[i][j].colourInit();
                        ghostPx[i][j].draw(color(234, 130, 229));
                    }
                }
            }
            drawGhostEyes(ghost2);
            resetMatrix();
        }
        if (!ghost3.dir.equals("stopped") || showGhostWhenStopped) {
            translate(ghost3.x - 15, ghost3.y - 15);
            for (int i = 0; i < ghostPx.length; i++) {
                for (int j = 0; j < ghostPx.length; j++) {
                    if ((i == 14 || i == 13) && (frameCount - startFrames) % 100 < 45) {
                        ghostBottom2Px[i - 13][j].colourInit();
                        ghostBottom2Px[i - 13][j].draw(color(70, 191, 238));
                    } else {
                        ghostPx[i][j].colourInit();
                        ghostPx[i][j].draw(color(70, 191, 238));
                    }
                }
            }
            drawGhostEyes(ghost3);
            resetMatrix();
        }
    }

    public String createRDir(int posX, int posY) {
        int tempVar = Math.round(random(3));
        String possDir = makeDir(tempVar);
        while (checkGoodDir(possDir, posX, posY)) {
            tempVar = makeDirNum();
            possDir = makeDir(tempVar);
        }
        return possDir;
    }

    public void controlGhostMovement(int pos1x, int pos1y, int pos2x, int pos2y, int pos3x, int pos3y) {
        if (checkGoodDir(ghost1.dir, pos1x, pos1y)) {
            ghost1.dir = createRDir(pos1x, pos1y);
        }
        if (checkGoodDir(ghost2.dir, pos2x, pos2y)) {
            ghost2.dir = createRDir(pos2x, pos2y);
        }
        if (checkGoodDir(ghost3.dir, pos3x, pos3y)) {
            ghost3.dir = createRDir(pos3x, pos3y);
        }
    }

    //// OBJECTS \\\\
    public class Ghost {
        float x, y;
        String dir;

        Ghost() {
            x = createPosition(true);
            y = createPosition(false);
            dir = "up";
        }

        public void update(int coordsX, int coordsY) {
            switch (dir) {
                case "up" -> {
                    if (coordsY - 1 >= 0) {
                        if (cells[coordsX][coordsY - 1].open) {
                            x = coordsX * cellWidth + (cellWidth / 2f);
                            y -= ghostSpeed;
                        }
                    }
                }
                case "down" -> {
                    if (coordsY + 1 <= height / cellWidth) {
                        if (cells[coordsX][coordsY + 1].open) {
                            x = coordsX * cellWidth + (cellWidth / 2f);
                            y += ghostSpeed;
                        }
                    }
                }
                case "right" -> {
                    if (coordsX + 1 <= width / cellWidth) {
                        if (cells[coordsX + 1][coordsY].open) {
                            y = coordsY * cellWidth + (cellWidth / 2f);
                            x += ghostSpeed;
                        }
                    }
                }
                case "left" -> {
                    if (coordsX - 1 >= 0) {
                        if (cells[coordsX - 1][coordsY].open) {
                            y = coordsY * cellWidth + (cellWidth / 2f);
                            x -= ghostSpeed;
                        }
                    }
                }
            }
            if (dist(x, y, pacman.x, pacman.y) < cellWidth / 2f) {
                if (x >= cellWidth * 2) {
                    lostLife = true;
                }
            }
        }

        public void up() {
            dir = "up";
        }

        public void right() {
            dir = "right";
        }

        public void halt() {
            //stopped = true;
            dir = "stopped";
        }

        public void newGame() {
            x = createPosition(true);
            y = createPosition(false);
        }

        public void goodPosition(int coordsX, int coordsY) {
            if (!cells[coordsX][coordsY].open) {
                newGame();
                messages = splice(messages, "Adjustment in Progress...", 0);
            }
            if (coordsX == 1) {
                right();
            }
            if (x > canvasWidth - cellWidth || x < cellWidth || y > canvasHeight - cellWidth || y < cellWidth) {
                messages = splice(messages, "Adjustment in Progress...", 0);
                newGame();
            }
        }
    }

    // Cell \\
    class Cell {
        final int x;
        final int y;
        boolean open;

        Cell(int x1, int y1) {
            x = x1;
            y = y1;
        }

        public void show(int colour, boolean all) {
            if (all) {
                if (!open) {
                    fill(colour);
                    rect(x, y, cellWidth, cellWidth);
                }
            } else {
                if (open) {
                    fill(0);
                    rect(x, y, cellWidth, cellWidth);
                }
            }
        }
    }


    //// Pellet \\\\
    class Pellet {
        int x, y;
        boolean eaten = false, isFruit = false;
        String fruitType = "cherry";

        Pellet(int x1, int y1) {
            x = x1;
            y = y1;
        }

        public void update() {
            pelletsEaten = 0;
            eaten = false;
            if (isFruit) {
                fruitWorth = 100;
            }
        }

        public void isBEaten() throws FileNotFoundException {
            if (!eaten && dist(x, y, pacman.x, pacman.y) < cellWidth / 8f + pacman.size / 8f) {
                if (isFruit) {
                    switch (fruitType) {
                        case "cherry" -> fruitWorth = 100;
                        case "strawberry" -> fruitWorth = 300;
                        case "orange" -> fruitWorth = 500;
                        case "apple" -> fruitWorth = 700;
                        case "melon" -> fruitWorth = 1000;
                        case "galaxian" -> fruitWorth = 2000;
                        case "bell" -> fruitWorth = 3000;
                        case "key" -> fruitWorth = 5000;
                    }
                    score += fruitWorth;
                    fruit.play();
                } else {
                    if (!pelletFirst) {
                        dotSound2.play();
                        pelletFirst = true;
                    } else {
                        dotSound1.play();
                        pelletFirst = false;
                    }
                    score += pelletWorth;
                    pelletsEaten++;
                }
                eaten = true;
                giveLives();
                messages = splice(messages, "Your score is:" + str(score), 0);
                increaseHighScore();
            }
        }

        public void draw() {
            if (!eaten) {
                noStroke();
                if (isFruit) {
                    switch (fruitType) {
                        case "strawberry" -> image(strawberry, x, y, cellWidth, cellWidth);
                        case "orange" -> image(orange, x, y, cellWidth, cellWidth);
                        case "apple" -> image(apple, x, y, cellWidth, cellWidth);
                        case "melon" -> image(melon, x, y, cellWidth, cellWidth);
                        case "galaxian" -> image(galaxian, x, y, cellWidth, cellWidth);
                        case "bell" -> image(bell, x, y, cellWidth, cellWidth);
                        case "key" -> image(keyI, x, y, cellWidth, cellWidth);
                        default -> image(cherry, x, y, cellWidth, cellWidth);
                    }
                } else {
                    noStroke();
                    fill(255, 150, 0);
                    ellipse(x, y, cellWidth / 2f - 1, cellWidth / 2f - 1);
                }
            }
        }

        public void goodPosition(int coordsX1, int coordsY1) {
            boolean a = false;
            if (coordsY1 == 1 && !isFruit) {
                if (coordsX1 == 1 || coordsX1 == 8) {
                    a = true;
                }
            }
            if (!cells[coordsX1][coordsY1].open || a) {
                update();
                x = createPosition(true);
                y = createPosition(false);
                while (dist(x, y, pacman.x, pacman.y) < cellWidth / 2f) {
                    x = createPosition(true);
                    y = createPosition(false);
                }
                fill(255, 128, 255);
                ellipse(x, y, cellWidth / 2f - 1, cellWidth / 2f - 1);
                pelletErrors++;
                messages = splice(messages, "Adjustment in Progress...", 0);
                messages = splice(messages, str(pelletErrors) + "pellet(s) were misplaced", 0);
                makePelletCoords();
            }
            if (isFruit) {
                y = Math.round(cellWidth * 1.5f);
            }
        }
    }

    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Pacman~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    class Pacman {
        final int size = Math.round(cellWidth - 1);
        final float speed = pacmanSpeed * ((cellWidth + 32) / 2) / 32f;
        final int stopBuffer = 2;
        boolean stopped = true;
        float x = cellWidth / 2f + cellWidth;
        float y = cellWidth / 2f + cellWidth;

        String nextDir = "stopped", dir = "stopped", lastDir = "stopped";

        public void show(float mouthSize) {
            float mouthOpenTop, mouthOpenBottom;
            /*if (Float.isNaN(mouthSize)) {
                mouthSize = 16;
            }*/
            if (stopped && !startsWMouth) {
                mouthSize = 0;
                if (playStartSound) {
                    startSound.play();
                    playStartSound = false;
                }
            }
            fill(255, 255, 0);
            translate(x, y);
            switch (lastDir) {
                case "up" -> rotate(PI + HALF_PI);
                case "down" -> rotate(HALF_PI);
                case "left" -> rotate(PI);
            }
            mouthOpenTop = map(mouthSize, 0, 60, 0, 0.52f);
            mouthOpenBottom = map(mouthSize, 0, 60, TWO_PI, 5.76f);
            arc(0, 0, (cellWidth * 15) / 16f, (cellWidth * 15) / 16f, mouthOpenTop, mouthOpenBottom);
            resetMatrix();
        }

        public void update() {
            //StackTraceElement[] stacktrace = Thread.currentThread().getStackTrace();
            //maybe this number needs to be corrected
            //println((frameCount/2)%6+": "+stacktrace[frameCount%6].getMethodName());
            coordsX = Math.round(x / cellWidth + 0.5f) - 1;
            coordsY = Math.round(y / cellWidth + 0.5f) - 1;
            if (pelletsEaten >= pellet.length - 1) {
                for (Pellet value : pellet) {
                    value.update();
                }
                first = false;
                coordsX = 1;
                coordsY = 1;
                x = cellWidth * 1.5f;
                y = cellWidth * 1.5f;
                dir = "stopped";
                nextDir = "stopped";
            }
            switch (nextDir) {
                case "up" -> {
                    if (cells[coordsX][coordsY - 1].open) {
                        dir = nextDir;
                        x = coordsX * cellWidth + (cellWidth / 2f);
                    }/* else {
                        if (other && !nextDir.equals(dir)) {
                            messages = splice(messages, "I want to move up", 0);
                        }
                    }*/
                }
                case "down" -> {
                    if (cells[coordsX][coordsY + 1].open) {
                        dir = nextDir;
                        x = coordsX * cellWidth + (cellWidth / 2f);
                    }/* else {
                        if (other && !nextDir.equals(dir)) {
                            messages = splice(messages, "I want to move down", 0);
                        }
                    }*/
                }
                case "right" -> {
                    if (cells[coordsX + 1][coordsY].open) {
                        dir = nextDir;
                        y = coordsY * cellWidth + (cellWidth / 2f);
                    }/* else {
                        if (other && !nextDir.equals(dir)) {
                            messages = splice(messages, "I want to move right", 0);
                        }
                    }*/
                }
                case "left" -> {
                    if (cells[coordsX - 1][coordsY].open) {
                        dir = nextDir;
                        y = coordsY * cellWidth + (cellWidth / 2f);
                    }/* else {
                        if (other && !nextDir.equals(dir)) {
                            messages = splice(messages, "I want to move left", 0);
                        }
                    }*/
                }
            }


            switch (dir) {
                case "up" -> {
                    if (cells[coordsX][coordsY - 1].open) {
                        y -= speed;
                        stopped = false;
                        if (x < coordsX * cellWidth + (cellWidth / 2f)) {
                            x += speed;
                        }
                        if (x > coordsX * cellWidth + (cellWidth / 2f)) {
                            x -= speed;
                        }
                        lastDir = "up";
                    } else {
                        if (y <= (coordsY * cellWidth + (cellWidth / 2f)) + stopBuffer) {
                            dir = nextDir;
                            nextDir = "stopped";
                        } else {
                            y -= speed;
                        }
                    }

                }
                case "down" -> {
                    if (cells[coordsX][coordsY + 1].open) {
                        y += speed;
                        stopped = false;
                        if (x < coordsX * cellWidth + (cellWidth / 2f)) {
                            x += speed;
                        }
                        if (x > coordsX * cellWidth + (cellWidth / 2f)) {
                            x -= speed;
                        }
                        lastDir = "down";
                    } else {
                        if (y >= (coordsY * cellWidth + (cellWidth / 2f)) - stopBuffer) {
                            dir = nextDir;
                            nextDir = "stopped";
                        } else {
                            y += speed;
                        }
                    }

                }
                case "right" -> {

                    if (cells[coordsX + 1][coordsY].open) {
                        x += speed;
                        stopped = false;
                        if (y < coordsY * cellWidth + (cellWidth / 2f)) {
                            y += speed;
                        }
                        if (y > coordsY * cellWidth + (cellWidth / 2f)) {
                            y -= speed;
                        }
                        lastDir = "right";
                    } else {
                        if (x >= (coordsX * cellWidth + (cellWidth / 2f)) - stopBuffer) {
                            dir = nextDir;
                            nextDir = "stopped";
                        } else {
                            x += speed;
                        }
                    }
                }
                case "left" -> {

                    if (cells[coordsX - 1][coordsY].open) {
                        x -= speed;

                        stopped = false;
                        if (y < coordsY * cellWidth + (cellWidth / 2f)) {
                            y += speed;
                        }
                        if (y > coordsY * cellWidth + (cellWidth / 2f)) {
                            y -= speed;
                        }
                        lastDir = "left";
                    } else {
                        if (x <= (coordsX * cellWidth + (cellWidth / 2f)) + stopBuffer) {
                            dir = nextDir;
                            nextDir = "stopped";
                        } else {
                            x -= speed;
                        }
                    }
                }
                case "stopped" -> {
                    if (x < coordsX * cellWidth + (cellWidth / 2f)) {
                        x += speed;
                    }
                    if (x > coordsX * cellWidth + (cellWidth / 2f)) {
                        x -= speed;
                    }
                    if (y < coordsY * cellWidth + (cellWidth / 2f)) {
                        y += speed;
                    }
                    if (y > coordsY * cellWidth + (cellWidth / 2f)) {
                        y -= speed;
                    }
                }
            }
            if (x > 400) {
                x = cellWidth + size / 2f;
            }
            if (y > 400) {
                y = cellWidth + size / 2f;
            }
            coordsX = Math.round(x / cellWidth + 0.5f) - 1;
            coordsY = Math.round(y / cellWidth + 0.5f) - 1;
        }

        public void up() {
            coordsX = Math.round((x) / cellWidth + 0.5f) - 1;
            coordsY = Math.round((y) / cellWidth + 0.5f) - 1;
            if (cells[coordsX][coordsY - 1].open) {
                dir = "up";
                nextDir = "up";
                if (x < coordsX * cellWidth + (cellWidth / 2f)) {
                    x += speed;
                }
                if (x > coordsX * cellWidth + (cellWidth / 2f)) {
                    x -= speed;
                }
            } else {
                nextDir = "up";
            }

            // }
        }

        public void down() {
            coordsX = Math.round((x) / cellWidth + 0.5f) - 1;
            coordsY = Math.round((y) / cellWidth + 0.5f) - 1;
            if (cells[coordsX][coordsY + 1].open) {
                dir = "down";
                nextDir = "down";
                if (x < coordsX * cellWidth + (cellWidth / 2f)) {
                    x += speed;
                }
                if (x > coordsX * cellWidth + (cellWidth / 2f)) {
                    x -= speed;
                }
            } else {
                nextDir = "down";
            }


        }

        public void right() {
            coordsX = Math.round((x) / cellWidth + 0.5f) - 1;
            coordsY = Math.round((y) / cellWidth + 0.5f) - 1;
            if (cells[coordsX + 1][coordsY].open) {
                dir = "right";
                nextDir = "right";
                if (y < coordsY * cellWidth + (cellWidth / 2f)) {
                    y += speed;
                }
                if (y > coordsY * cellWidth + (cellWidth / 2f)) {
                    y -= speed;
                }
            } else {
                nextDir = "right";
            }


        }

        public void left() {
            coordsX = Math.round((x) / cellWidth + 0.5f) - 1;
            coordsY = Math.round((y) / cellWidth + 0.5f) - 1;
            if (cells[coordsX - 1][coordsY].open) {
                dir = "left";
                nextDir = "left";
                if (y < coordsY * cellWidth + (cellWidth / 2f)) {
                    y += speed;
                }
                if (y > coordsY * cellWidth + (cellWidth / 2f)) {
                    y -= speed;
                }
            } else {
                nextDir = "left";
            }

        }


        public void stop() {
            dir = "stopped";
            stopped = false;
            nextDir = "stopped";
        }
    }

    class Pixel {
        static int size;
        final int colourCode;
        final float x;
        final float y;
        int colour;

        Pixel(int colourCode1, float x1, float y1) {
            colourCode = colourCode1;
            size = 2;
            x = x1;
            y = y1;
        }

        public void colourInit() {
            switch (colourCode) {
                case 0 -> colour = color(255, 0);
                case 2, 3 -> colour = color(255);
                default -> colour = color(255, 0, 0);
            }
        }


        public void draw(int gColour) {
            if (colourCode == 1) {
                colour = gColour;
            }
            rectMode(CENTER);
            fill(colour);
            rect(x, y, size, size);
            rectMode(CORNER);
        }
    }
}
